// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zydgfthgradetpmxiqrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5ZGdmdGhncmFkZXRwbXhpcXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTczMzksImV4cCI6MjA1OTU3MzMzOX0.WedgtYE6TLwhFCBhSBN-iSNiVU4C1oBMAyRLA2kC204";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);